import { BaseLayout } from '@/components/BaseLayout'
import { Analytics } from '@vercel/analytics/react'
import Head from 'next/head'
import Script from 'next/script'
import React from 'react'
import { CustomApp } from './page'
import './reset.css'
import './globals.css'

const GA_ID = process.env.NEXT_PUBLIC_GA_ID || ''

export default function MyApp({ Component, pageProps }: CustomApp) {
  const pageTitle = Component.getTitle?.(pageProps) ?? ''
  const getLayout =
    Component.getLayout ?? ((page) => <BaseLayout header>{page}</BaseLayout>)
  const title = `akfm.dev${pageTitle ? ` - ${pageTitle}` : ''}`

  return getLayout(
    <>
      <Head>
        <title>{title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.svg" />
      </Head>
      <Component {...pageProps} />
      <Analytics />
      <Script
        src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_ID}');
        `}
      </Script>
    </>
  )
}
