import { Footer } from '@/components/Footer'
import Head from 'next/head'
import React from 'react'
import { CustomApp } from './page'
import './reset.css'
import './globals.css'
import styles from './app.module.css'

export default function MyApp({ Component, pageProps }: CustomApp) {
  const pageTitle = Component.getTitle?.(pageProps) ?? ''
  const title = `akfm.dev${pageTitle ? ` - ${pageTitle}` : ''}`

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.svg" />
      </Head>
      <div className={styles.container}>
        <div className={styles.contents}>
          <div className={styles.inner}>
            <Component {...pageProps} />
          </div>
          <Footer />
        </div>
      </div>
    </>
  )
}
