import { BaseLayout } from '@/components/BaseLayout'
import Head from 'next/head'
import React from 'react'
import { CustomApp } from './page'
import './reset.css'
import './globals.css'

export default function MyApp({ Component, pageProps }: CustomApp) {
  const pageTitle = Component.getTitle?.(pageProps) ?? ''
  const getLayout =
    Component.getLayout ?? ((page) => <BaseLayout header>{page}</BaseLayout>)
  const title = `akfm.dev${pageTitle ? ` - ${pageTitle}` : ''}`

  return getLayout(
    <>
      <Head>
        <title>{title}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.svg" />
      </Head>
      <Component {...pageProps} />
    </>
  )
}
