import { Analytics } from "@vercel/analytics/react";
import Head from "next/head";
import Script from "next/script";
import type React from "react";
import styles from "./Layout.module.css";
import "./globals.css";

export const metadata = {
  title: "akfm.dev",
};

const GA_ID = process.env.NEXT_PUBLIC_GA_ID || "";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <Head>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.svg" />
      </Head>
      <body>
        <div className={styles.outer}>
          <div className={styles.container}>
            <div className={styles.inner}>{children}</div>
            <footer className={styles.footer}>
              <p className={styles.copyright}>
                ©︎akfm.dev 2022. Using&nbsp;
                <a
                  href="https://www.google.com/intl/ja/policies/privacy/partners/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Google Analytics
                </a>
              </p>
            </footer>
          </div>
        </div>
        <Analytics />
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){window.dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${GA_ID}');
        `}
        </Script>
      </body>
    </html>
  );
}
