import Head from "next/head";
import React from "react";
import "./globals.css";
import { CustomApp } from "./page";
import "./reset.css";

export default function MyApp({ Component, pageProps }: CustomApp) {
  const title = Component.getTitle?.(pageProps) ?? "";
  return (
    <>
      <Head>
        <title>akfm.dev{title ? ` ${title}` : ""}</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.svg" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
